version: '3.7'

services:
    
    db:
      restart: always
      image: postgres
      container_name: ecom-postgres
      environment:
        - POSTGRES_USER=Dhruv
        - POSTGRES_PASSWORD=Dhruv@1304
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PORT=${POSTGRES_PORT}
      ports:
        - "5432:5432"

    pgadmin:
      restart: always
      image: dpage/pgadmin4
      container_name: ecom-pgadmin
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin

        